# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#source 'https://github.com/CocoaPods/Specs.git'

target 'UniLoginDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'UniLogin', '~> 0.0.4'
  pod 'WechatOpenSDK'
  
  target 'UniLoginDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UniLoginDemoUITests' do
    # Pods for testing
  end

end
